// initial input variables
kLeft = false ;
kLeftPressed = false ;
kRight = false ;
kRightPressed = false ;
kUp = false ;
kUpPressed = false ;
kDown = false ;
kDownPressed = false ;
kJump = false ;
kJumpPressed = false ;
kWeaponPressed = false ;
kSwitchWeaponPressed = false ;
kShield = false ;
kDigLeftPressed = false ;
kDigRightPressed = false ;
kNone = true ;
