globalvar vk_a, vk_b, vk_c, vk_d, vk_e, vk_f, vk_g, vk_h ;
globalvar vk_i, vk_j, vk_k, vk_l, vk_m, vk_n, vk_o, vk_p ;
globalvar vk_q, vk_r, vk_s, vk_t, vk_u, vk_v, vk_w, vk_x ;
globalvar vk_y, vk_z, vk_1, vk_2, vk_3, vk_4, vk_5, vk_6 ;
globalvar vk_7, vk_8, vk_9, vk_0 ;

vk_a = ord('A') ;
vk_b = ord('B') ;
vk_c = ord('C') ;
vk_d = ord('D') ;
vk_e = ord('E') ;
vk_f = ord('F') ;
vk_g = ord('G') ;
vk_h = ord('H') ;
vk_i = ord('I') ;
vk_j = ord('J') ;
vk_k = ord('K') ;
vk_l = ord('L') ;
vk_m = ord('M') ;
vk_n = ord('N') ;
vk_o = ord('O') ;
vk_p = ord('P') ;
vk_q = ord('Q') ;
vk_r = ord('R') ;
vk_s = ord('S') ;
vk_t = ord('T') ;
vk_u = ord('U') ;
vk_v = ord('V') ;
vk_w = ord('W') ;
vk_x = ord('X') ;
vk_y = ord('Y') ;
vk_z = ord('Z') ;
vk_1 = ord('1') ;
vk_2 = ord('2') ;
vk_3 = ord('3') ;
vk_4 = ord('4') ;
vk_5 = ord('5') ;
vk_6 = ord('6') ;
vk_7 = ord('7') ;
vk_8 = ord('8') ;
vk_9 = ord('9') ;
vk_0 = ord('0') ;
